services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-scheduler:
    image: airflow_custom_image
    build: .
    depends_on:
      - postgres
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/home/airflow/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=github-events-analysis
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=google-cloud-platform://?project=github-events-analysis
    volumes:
      - ./scripts:/opt/airflow/scripts
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: >
      bash -c "
        sleep 15 &&
        airflow db migrate &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@admin.com --password admin || true &&
        airflow scheduler
      "

  airflow-webserver:
    image: airflow_custom_image
    build: .
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=google-cloud-platform://?project=github-events-analysis
    volumes:
      - ./scripts:/opt/scripts
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: > 
      bash -c "sleep 20 && airflow webserver && sleep 20"
